### DISCUSSION TITLE
Square boxes using a css-snippet?

### DISCUSSION THREAD

**Discussion by tmummert** [Richardsl/heatmap-calendar-obsidian#84] [Q&A] [answered]
Currently the boxes in my heatmaps have rectangular shape. Can they be made square using a css snippet? Are rounded corners also possible?

Thanks a lot in advance!

![image](https://github.com/Richardsl/heatmap-calendar-obsidian/assets/23436447/b55f3e55-3d82-4f8c-a346-295511f4461c)

**Comment by samgiz** [comment, marked as answer]
This might help:

```css
.heatmap-calendar-boxes li {
    /* Make boxes square */
    aspect-ratio: 1;
    /* I believe you should be able to use `border-radius` for rounded corners here */
}

/* This removes the `Mon`/`Wed`/`Fri`/`Sun` labels, otherwise I find the heatmap looks wonky when the note width is small */
.heatmap-calendar-days {
    display: none;
}
```
