### ISSUE TITLE
FEATURE REQUEST: link to daily note on hover

### ISSUE THREAD

**Issue by ka1tzyu** [Richardsl/heatmap-calendar-obsidian#12]
It would be nice to be able to jump to a specific note when hovering over a square

**Comment by arsenty** [comment]
@ka1tzyu, here is simple solution:

```js
calendarData.entries.push({
        date: page.file.name,
        intensity: intensity,
        content: await dv.span(`[](${page.file.name})`)
})
```

and custom css to expand clickable area on entire a square:
```css
.heatmap-calendar-boxes li {
    position: relative;
}
.heatmap-calendar-boxes li:not(.task-list-item)::before {
    content: unset;
}
.heatmap-calendar-boxes .internal-link {
    text-decoration: none;
    position: absolute;
    width: 100%;
    height: 100%;
}
```
