### ISSUE TITLE
Make the frame marking today more visible in dark mode

### ISSUE THREAD

**Issue by truscobox** [Richardsl/heatmap-calendar-obsidian#143]
When there is no marking for the current day and Obsidian is set to dark mode, the marking frame for today is barely visible. Maybe a solution would be to change the color to a brighter shade of gray to better discern it.

**Comment by Opti-Digital** [comment]
+1 on above.


In the mean time I am using below CSS Snippet to override the colour specifically for dark theme today border:
```css
/* HeatMap Plugin */
.theme-dark .heatmap-calendar-boxes .today {
	border-color: #FFFFFF; /* Change today border colour to WHITE */
}
```

You can adjust the colour to anything you like by adjusting the `#FFFFFF` value.

Note: You can make the border only appear when there is data for the current day using the css below (adding `.hasData` class condition):
```css
/* HeatMap Plugin */
.theme-dark .heatmap-calendar-boxes .today.hasData {
	border-color: #FFFFFF; /* Change today border colour to WHITE */
}
```
