### ISSUE TITLE
Today marker is barely visible for dark themes, as there's no separate dark mode style for it

### ISSUE THREAD

**Issue by scorchio** [Richardsl/heatmap-calendar-obsidian#44]
Hi - Could you please add a separate dark mode version for the `.heatmap-calendar-boxes .today` CSS rule? I think it would help a lot with the visibility of the marker. 

I think adding something like this 
```css
.theme-dark .heatmap-calendar-boxes .today {
  border: 1px solid rgb(180, 180, 180);
}
```
would do the trick.
